# Artificial Neural Network

### Importing the libraries

In [155]:
import numpy as np 
import pandas as pd 
import tensorflow as tf



In [156]:
tf.__version__

'2.10.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [157]:
# Data preprocessing is about 70% of the work of a data scientist 
dataset = pd.read_csv('Churn_Modelling.csv')
# [rows, columns]
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [158]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [159]:
# 1 left the bank 1, stayed 0
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [160]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
# Female column will be incoded into 0 and Male 1 
X[:, 2] = le.fit_transform(X[:, 2])

In [161]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [162]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# It will create a matrix with France, Spain, Germany
# France  1.0 0.0 0.0
# Spain   0.0 0.0 1.0
# Germany 0.0 1.0 0.0
ct = ColumnTransformer(transformers = [( 'encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [163]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [164]:
from sklearn.model_selection import train_test_split
# splits the dataset into training and testing sets, with 80% of the data used for training and 20% used for testing.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [165]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


### Feature Scaling

In [166]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# It is only fitted to the training to avoid information leaked 
# to normalize the features in order to ensure that they are on a similar scale, which can help improve the
# performance and convergence of machine learning algorithms
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [167]:
# Create a variable that will be a NN which will be an object of acertain class artificial neural network 
# Initializing the nn as a sequence of layers 
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [168]:
# Add a fully connected layer into an ANN at whatever phase
# rectifier activation = relu
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu',))

### Adding the second hidden layer

In [169]:
# It will have 6 hidden neurons - second hidden layer 
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [170]:
# The add method can add any layer, the dense class is the thing that keeps the connectino between layers
# Since our output is 0-1 then we only need one neuron to predict that output 
# Sigmoid activation function 
# when your output is not binary use softmax instead of sigmoid
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))


## Part 3 - Training the ANN

### Compiling the ANN

In [171]:
# When not binary category_crossentropy
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [172]:
# fit method will train your ann
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 420us/step - loss: 0.6831 - accuracy: 0.6406
Epoch 2/100
250/250 [==============================] - 0s 435us/step - loss: 0.5156 - accuracy: 0.7951
Epoch 3/100
250/250 [==============================] - 0s 510us/step - loss: 0.4834 - accuracy: 0.7961
Epoch 4/100
250/250 [==============================] - 0s 442us/step - loss: 0.4595 - accuracy: 0.7996
Epoch 5/100
250/250 [==============================] - 0s 466us/step - loss: 0.4371 - accuracy: 0.8092
Epoch 6/100
250/250 [==============================] - 0s 504us/step - loss: 0.4207 - accuracy: 0.8174
Epoch 7/100
250/250 [==============================] - 0s 486us/step - loss: 0.4085 - accuracy: 0.8207
Epoch 8/100
250/250 [==============================] - 0s 463us/step - loss: 0.3968 - accuracy: 0.8307
Epoch 9/100
250/250 [==============================] - 0s 490us/step - loss: 0.3859 - accuracy: 0.8359
Epoch 10/100
250/250 [==============================] - 0s 447us/step - l

250/250 [==============================] - 0s 441us/step - loss: 0.3368 - accuracy: 0.8619
Epoch 80/100
250/250 [==============================] - 0s 423us/step - loss: 0.3365 - accuracy: 0.8610
Epoch 81/100
250/250 [==============================] - 0s 544us/step - loss: 0.3362 - accuracy: 0.8634
Epoch 82/100
250/250 [==============================] - 0s 552us/step - loss: 0.3367 - accuracy: 0.8627
Epoch 83/100
250/250 [==============================] - 0s 440us/step - loss: 0.3362 - accuracy: 0.8624
Epoch 84/100
250/250 [==============================] - 0s 475us/step - loss: 0.3363 - accuracy: 0.8659
Epoch 85/100
250/250 [==============================] - 0s 484us/step - loss: 0.3356 - accuracy: 0.8631
Epoch 86/100
250/250 [==============================] - 0s 489us/step - loss: 0.3356 - accuracy: 0.8626
Epoch 87/100
250/250 [==============================] - 0s 434us/step - loss: 0.3354 - accuracy: 0.8635
Epoch 88/100
250/250 [==============================] - 0s 441us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [174]:
# Chances of leaving the bank? 
# Remember to scale your data 
# prediction1 = sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
# print(prediction)
# prediction = ann.predict(X_train[[1], :])
# print(X_test[[1],:])s
# if you stop working, just re-run all the code, and now everything makes sense
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))


1/1 [==============================] - 0s 10ms/step
[[0.03613352]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [175]:
y_pred = ann.predict(X_test)
# true = will leave the bank  = 1 else 0
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))
# So what this is saying is that we predict that [prediction, actual result]
# 1. we predicted that he stayed in the bank, and he actually stayed the bank
# 2. we predicted that he stayed, but he actually left 

63/63 [==============================] - 0s 366us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [176]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
# The value output will be our accuracy
# we have 1510 correct predictions
# then we have 211 predictions that the customer leaves the bank
# 85 incorrect predictions that the customer leaves the bank
# 194 incorrect predictions that the customer stayed 

[[1510   85]
 [ 194  211]]


0.8605